Programador = str (input ("Digite algo "))
print (type(Programador))
print ("A variável é printável?", Programador.isprintable())
print ("A variável é alphanumérica?", Programador.isalnum())
print ("A variável é numérica?", Programador.isnumeric())
print ("A variável é alphabética?", Programador.isalpha())
print ("A variável é espaço?", Programador.isspace())
print ("A variável está em maiúsculas?", Programador.isupper())
print ("A variável está em minúsculas?", Programador.islower())
print ("A variável está capitalizada?", Programador.istitle())
